version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/code
    ports:
      - '8000:8000'
    command: tail -f /dev/null
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - USER_NAME
      - USER_ID
      - GROUP_NAME
      - GROUP_ID
    volumes:
      - ./frontend:/code
    ports:
      - '3000:3000'
    command: tail -f /dev/null
    depends_on:
      - backend
